church1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts')),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('new/', views.CreatePostView.as_view(), name='post_new'),
    path('<int:pk>/edit/', views.UpdatePostView.as_view(), name='post_edit'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('chuch/<int:pk>/', views.ChurchDetail.as_view(), name='church_detail'),
    path('chuch/<int:pk>/contact/', views.emailView, name='contact')
    #path('chuch/<int:pk>/contact/', views.ChurchContact.as_view(), name='church_contact')
]

volunteer-platform/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts')),
]

users/models.py
from django.db import models
from address.models import AddressField
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager



# Create your models here.

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    phone_number = PhoneNumberField()
    church_name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000, blank=True)
    #denomination = models.CharField(max_length=200)
    address = AddressField(on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['church_name', 'phone_number','address']

    objects = CustomUserManager()

    def __str__(self):
        return self.church_name

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from address.models import AddressField
from phonenumber_field.formfields import PhoneNumberField

from .models import CustomUser
from django.db import models
from django import forms


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        address = AddressField()
        model = CustomUser
        fields = ('church_name','address', 'phone_number', 'email', 'password1', 'password2','is_staff')



class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)


class ContactForm(forms.Form):
    user = forms.CharField(required=True, label='Your Name' )
    email = forms.EmailField(required=True, label='Email')
    phone = PhoneNumberField()
    message = forms.CharField(widget=forms.Textarea, required=True, max_length=1000)

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import CreateView, DetailView
from django.urls import reverse_lazy
from django.core.mail import send_mail, BadHeaderError

from . import forms
from . import models

# Create your views here.

class SignUpView(CreateView):
    form_class = forms.CustomUserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/signup.html'

class ChurchDetail(DetailView):
    model = models.CustomUser
    template_name = 'users/church_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['church'] = models.CustomUser.objects.all()
        return context


class ChurchContact(DetailView):
    model = models.CustomUser
    template_name = 'users/church_contact.html'


def emailView(request, pk):

    if request.method == 'GET':
        form = forms.ContactForm()
        church = models.CustomUser.objects.get(pk=pk)
        church_dict = {'church':church}
    else:
        form = forms.ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['user']
            from_email = 'noreply@jonezfam.com'
            message = 'From: '+form.cleaned_data['user']+' Email:'+form.cleaned_data['email']+'Phone:'+str(form.cleaned_data['phone'])+' Message:'+form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email, ['timjonez@protonmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('home')
    return render(request, "users/contact.html", {'form': form, 'church':church})

users/templates/users/church_detail.html
{% extends 'base.html' %}

{% block content %}

  <div class="church_detail">
    <h1>{{customuser.church_name}}</h1>
    <h5>{{customuser.address}}</h5>
    <p>{{customuser.description}}</p>

    <a class='btn btn-secondary' href="{% url 'users:contact' pk=customuser.pk %}">Contact</a>
  </div>

{% endblock %}

users/templates/users/contact.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-6" id='contact_form' >
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <button class="btn btn-secondary" type="submit">Contact</button>
        </form>
      </div>

      <a id="contact_info" class="col-lg-4" href="{% url 'users:church_detail' pk=church.pk%}">
        <h1>{{church.church_name}}</h1>
        <p>{{church.address.street_number}} {{church.address.route}}<br>
           {{church.address.locality.name}}, {{church.address.locality.state.name}}, {{church.address.locality.postal_code}}<br>
           {{church.email}}<br>
           {{church.phone_number}}
        </p>
      </a>

    </div>
  </div>



{% endblock %}

users/templates/users/login.html
{% extends 'base.html'%}

{% load bootstrap4 %}

{% block content %}

  <div class="container">

    <div class="col-lg-4 login_page">
     <h1>Log In</h1>
     <form method="post">
       {% csrf_token %}
       {% bootstrap_form form %}
       <button type="submit" class="btn btn-secondary">Log In</button>
     </form>
     Don't have an account? <a href="{% url 'users:signup' %}">Sign Up</a>
     </div>
    </div>
{% endblock %}

users/templates/users/signup.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap4 %}
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>ChurchWorks</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
		<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		<link rel="stylesheet" href="{% static 'css/master.css'%}">
		{{ form.media }}
	</head>
	<body>

		<nav class=" navbar navbar-expand-lg navbar-light">

				<div class="navbar-nav align-items-center">

					<a class="custnav-brand" href="{% url 'home'%}"> <b>ChurchWorks</b>
					</a>
				</div>
				<div class="navbar-nav ml-auto">
						<a class="custnav-item" href="{% url 'posts:post_list'%}">Jobs</a>
					{% if user.is_authenticated %}
						<a class="custnav-item" href="{% url 'users:logout'%}">Logout</a>
					{% else %}
						<a class="custnav-item" href="{% url 'users:login'%}">Log In</a>
					{% endif %}
				</div>


		</nav>

	<div class="container">
		<div class="col-md-4 signup_page">

			 <h1>Sign Up</h1>
			 <form method="post">
					{% csrf_token %}
					{%bootstrap_form form%}
				 <button type="submit" class="btn btn-primary">Sign Up</button>
			 </form>
			 Already have an account? <a href="{% url 'users:login' %}">Log In</a>
		</div>
	</div>

	</body>
</html>