church1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts')),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('new/', views.CreatePostView.as_view(), name='post_new'),
    path('<int:pk>/edit/', views.UpdatePostView.as_view(), name='post_edit'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('chuch/<int:pk>/', views.ChurchDetail.as_view(), name='church_detail'),
    path('chuch/<int:pk>/contact/', views.emailView, name='contact')
    #path('chuch/<int:pk>/contact/', views.ChurchContact.as_view(), name='church_contact')
]

volunteer-platform/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ChurchWorks</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css'%}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
  <body>

    <nav class=" navbar navbar-expand-lg navbar-light">

        <div class="navbar-nav align-items-center">

          <a class="custnav-brand" href="{% url 'home'%}"> <b>ChurchWorks</b>
          </a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="custnav-item" href="{% url 'posts:post_new'%}">New Project</a>
          {% endif %}

          <a class="custnav-item" href="{% url 'posts:post_list'%}">Jobs</a>

          {% if user.is_authenticated %}
            <a class="custnav-item" href="{% url 'users:logout'%}">Logout</a>
          {% else %}
            <a class="custnav-item" href="{% url 'users:login'%}">Log In</a>
          {% endif %}
        </div>


    </nav>


    {% block content %}

    {% endblock %}


  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base.html'%}

{% block content %}
<div class="index-background">


  <div class="xcontainer">
    <div class="container">
      <div class="col-md-8" id='welcome'>

        <h1 id='card-title'>Volunteer!</h1><h3>Projects from churches all over the world</h3>

        <a class="btn btn-secondary btn-lg btn-block" href="{% url 'posts:post_list'%}">Find Projects</a>

      </div>
    </div>
  </div>
</div>

{% endblock %}