church1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts')),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('new/', views.CreatePostView.as_view(), name='post_new'),
    path('<int:pk>/edit/', views.UpdatePostView.as_view(), name='post_edit'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('chuch/<int:pk>/', views.ChurchDetail.as_view(), name='church_detail'),
    path('chuch/<int:pk>/contact/', views.emailView, name='contact')
    #path('chuch/<int:pk>/contact/', views.ChurchContact.as_view(), name='church_contact')
]

volunteer-platform/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('posts/', include('posts.urls', namespace='posts')),
]

posts/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

from users.models import CustomUser
# Create your models here.

class Category(models.Model):
    category_item = models.CharField(max_length=100, help_text='Category')

    def get_absolute_url(self):
        return reverse('posts:post_list')

    def __str__(self):
        return self.category_item

class Post(models.Model):
    user = models.ForeignKey(CustomUser, related_name='posts', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=200)
    body = models.TextField()
    label = models.ForeignKey(Category, verbose_name='Category', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('posts:post_list')


    def __str__(self):
        return self.title

posts/forms.py
from django import forms
import django_filters
import itertools
from . import models


class PostForm(forms.ModelForm):

    class Meta:
        model = models.Post
        fields = ('label','title','body')

class PostFilter(django_filters.FilterSet):
    search = django_filters.CharFilter(lookup_expr='icontains', field_name='body')


    class Meta:
        model = models.Post
        fields = ['label']

posts/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from functools import reduce
import operator
from django.db.models import Q
from .models import Post, Category
from .forms import PostForm, PostFilter
from django.http import HttpResponseForbidden

from django.views.generic import (CreateView, UpdateView,
                                  DeleteView, TemplateView,
                                  DetailView, ListView)

# Create your views here.
decorators = [user_passes_test(lambda u: u == obj.user)]

class CreatePostView(LoginRequiredMixin, CreateView):
    redirect_field_name = 'posts/post_detail.html'
    form_class = PostForm
    model = Post

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        return super().form_valid(form)


class MyPermissionMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if request.user != self.get_object().user:
            return HttpResponseForbidden()

        return super().dispatch(request, *args, **kwargs)


class UpdatePostView(MyPermissionMixin, UpdateView):
    redirect_field_name = 'posts/post_detail.html'
    form_class = PostForm
    model = Post

    def test_func(self):
        return self.request.session.get('issuer_pk', None) is not None



class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('posts:post_list')


def post_list(request):
    f = PostFilter(request.GET, queryset=Post.objects.all().order_by('-created_date'))
    return render(request, 'posts/post_list.html',{'filter':f})




class PostDetailView(DetailView):
    model = Post

posts/templates/posts/post_category.html
{% extends 'base.html' %}

{% block content %}

  <a href="{% url 'posts:post_new'%}">Add</a>




<!--
  <form class="searchfield" action="{% url 'posts:cat_search' pk="'x'"%}" method="get">
    <button  type="submit" name="button">
      <i class="fa fa-search"></i>
    </button>
    <input class="searchfield" id="searchbox" name='q' type="text" placeholder="Search">

  </form>
-->

  {% for post in post_list %}

       <a href="{% url 'posts:post_detail' pk=post.pk%}">{{ post.body }}</a>
        {{ post.label.id}}
        {{post.created_date}}
        {{post.text}}



  {% endfor%}




{% endblock %}

posts/templates/posts/post_delete.html
{% extends 'base.html' %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-lg-7" id='project'>
        <h1>{{post.title}}</h1>
        <h4>{{post.user}}</h4>

        <p>{{post.body}}</p>
        <a class="btn btn-secondary" href="{% url 'users:contact' pk=post.user.pk %}">Volunteer!</a>
        {% if user.is_authenticated%}
          <a href="{% url 'posts:post_edit' pk=post.pk%}">Edit</a>
        {% endif%}

      </div>
      <a id="about_href" class="col-lg-4" href="{% url 'users:church_detail' pk=post.user.pk%}">

        <h2>{{post.user}}</h2>
        <h6>{{post.user.address}}</h6>
        {{post.user.description}}

      </a>
    </div>
  </div>

{% endblock %}

posts/templates/posts/post_edit.html
{% extends 'base.html' %}

{%block content%}
<h1>Edit Page</h1>
{% endblock %}

posts/templates/posts/post_form.html
{% extends 'base.html' %}

{% load bootstrap4 %}
{% block content %}


    <div class="container">
      <form method="post" class="col-md-8" id='form' >
        {% csrf_token %}
        {%bootstrap_form form%}
        <button type="submit" class="btn btn-secondary">Publish</button>
      </form>
    </div>


{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}

  <div class=" container search-items">
    <div class="cont-search-items">
    <form method="get">
        <input class="btn btn-secondary mybtn" type="submit" value='Search'>
        <my id="search-box" >{{filter.form.search}}</my>
        <my id="search-cat-title"><b>Category:</b></my>
        <my id="search-dropdown">{{filter.form.label}}</my>
    </form>
  </div>
</div>
  <div class="post-list-page">

    <br>
    {% for post in filter.qs %}
      <div class="post">
        <h3><a id="post-list-title" href="{% url 'posts:post_detail' pk=post.pk%}">{{ post.title }}</a></h3>
        <h5>{{post.created_date|date:'m/d/yy'}}&nbsp;&nbsp;{{post.user}}</h5>
        <p>{{post.body|truncatechars:200}}</p>
      </div>
    {% endfor%}


  </div>





{% endblock %}

posts/templates/posts/post_list_filter.html
{% extends 'base.html' %}

{% block content %}





  <form class="searchfield" action="{% url 'posts:post_search'%}" method="get">
    <button  type="submit" name="button">
      <i class="fa fa-search"></i>
    </button>
    <input class="searchfield" id="searchbox" name='q' type="text" placeholder="Search">

  </form>


  <form method="get">
    {{filter.form.as_p}}
    <input type="submit">
  </form>


  {% for post in filter.qs %}
    <a href="{% url 'posts:post_detail' pk=post.pk%}">{{ post.title }}</a>


    {{post.created_date}}

    {{post.body}}
    {{view.categories.id}}
    <br>
  {% endfor%}

  {% for category in view.categories %}
   {{category.id}}
   {{category_pk}}
  {% endfor %}

{% endblock %}